name: 'Build Project'
description: 'Build a project'
inputs:
  project-name: 
    description: 'The name of the project'
    required: true
  project-path:
    description: 'The path to the project file (.sln or .csproj)'
    required: true
  project-path:
    description: 'The path to the project file (.sln or .csproj)'
    required: true
runs:
  using: "composite"
  steps: 
    - name: restore ${{ inputs.project-name }}
      run: nuget restore ${{ inputs.project-path }} -ConfigFile .nuget/Nuget.Config -PackagesDirectory packages -NonInteractive
      shell: powershell

    - name: Build ${{ inputs.project-name }}
      run: msbuild ${{ inputs.project-path }}
